name: "Make a test zip file"
on:
  workflow_call:

jobs:
  MakeZip:
    runs-on: ubuntu-latest
    steps:
      - name: Make zip with random content
        run: |
          echo "This is a test file." > test_file.md
      - name: Upload zip as artifact
        uses: actions/upload-artifact@v4
        with:
          name: test_zip
          path: test_file.md
