name: "Make a test zip file"
on:
  push:
    branches:
      - dev

jobs:
  MakeZip:
    runs-on: ubuntu-latest
    container:
      image: nefrock/edge_ocr_sdk:0.18
    steps:
      - name: Make zip with random content
        shell: bash
        run: |
          source ./scripts/dependencies.sh
          ./scripts/test_script.sh .
