name: "Comment on PR: Handle commands"
on:
  issue_comment:
    types: [created]

concurrency:
  group: pr-comment-reactions
  cancel-in-progress: false
jobs:
  RunTests:
    if: ${{ github.event.issue.pull_request && github.event.comment.body == '/run_tests' }}
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Label the PR
        run: |
          gh pr edit ${{ github.event.issue.number }} --repo ${{ github.repository }} --add-label "run-tests"
  SkipTests:
    if: ${{ github.event.issue.pull_request && github.event.comment.body == '/skip_tests' }}
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Label the PR
        run: gh pr edit ${{ github.event.issue.number }} --repo ${{ github.repository }} --add-label "skip-tests"

  FastForwardMerge:
    # Only run if the comment contains the /merge command.
    if: ${{ github.event.issue.pull_request && github.event.comment.body == '/merge' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
    steps:
      - name: Fast forwarding merging the PR
        uses: sequoia-pgp/fast-forward@v1
        with:
          merge: true
          # To reduce the workflow's verbosity, use 'on-error'
          # to only post a comment when an error occurs, or 'never' to
          # never post a comment.  (In all cases the information is
          # still available in the step's summary.)
          comment: always
