name: "Comment on PR: Handle commands"
on:
  issue_comment:
    types: [created]

concurrency:
  group: pr-comment-reactions
  cancel-in-progress: false
jobs:
  FFMerge:
    if: ${{ github.event.issue.pull_request && github.event.comment.body == '/merge' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      actions: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Get PR details
        id: pr_details
        run: |
          PR_NUMBER=${{ github.event.issue.number }}
          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_OUTPUT
          FROM_REF=$(gh pr view $PR_NUMBER --repo ${{ github.repository }} --json headRefName --jq .headRefName)
          echo "FROM_REF=$FROM_REF" >> $GITHUB_OUTPUT
          INTO_REF=$(gh pr view $PR_NUMBER --repo ${{ github.repository }} --json baseRefName --jq .baseRefName)
          echo "INTO_REF=$INTO_REF" >> $GITHUB_OUTPUT
      - uses: actions/checkout@v4
        with:
          ref: ${{ steps.pr_details.outputs.INTO_REF }}
      - name: Fast-Forward Merge PR
        id: ff_merge
        run: |
          git fetch origin ${{ steps.pr_details.outputs.FROM_REF }}
          git merge --ff-only origin/${{ steps.pr_details.outputs.FROM_REF }}
          git push origin HEAD:${{ steps.pr_details.outputs.INTO_REF }}
      - name: Post comment if ff merge fails
        if: ${{ failure() }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr comment ${{ github.event.issue.number }} \
            --repo ${{ github.repository }} \
            --body "Fast-Forward merge failed. Please resolve any conflicts or issues manually."
      - name: Manually trigger GitHub Action for PR after merge into dev
        if: ${{ success() && steps.pr_details.outputs.INTO_REF == 'dev' }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh workflow run pr_dev_tests.yml \
            --repo ${{ github.repository }} \
            --ref ${{ steps.pr_details.outputs.INTO_REF }}
