name: "Comment on PR: Handle commands"
on:
  issue_comment:
    types: [created]

concurrency:
  group: pr-comment-reactions
  cancel-in-progress: false
jobs:
  RunOrSkipTests:
    if: ${{ github.event.issue.pull_request && (github.event.comment.body == '/run_tests' || github.event.comment.body == '/skip_tests') }}
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: xt0rted/pull-request-comment-branch@v3
        if: ${{ github.event.comment.body == '/tests' }}
        id: get_refs
      - name: Ensure base is dev
        if: ${{ github.event.comment.body == '/tests' }}
        run: |
          echo "${{ steps.get_refs.outputs.base_ref }}"
          if [[ "${{ steps.get_refs.outputs.base_ref }}" != "dev" ]]; then
            echo "This PR must target the dev branch to run tests."
            exit 1
          fi
      - name: Label the PR
        run: |
          gh workflow run pr_dev_tests.yml \
            --repo ${{ github.repository }} \
            --ref ${{ steps.get_refs.outputs.head_ref }} \
            --field skip=${{ github.event.comment.body == '/skip_tests' }}

  FastForwardMerge:
    # Only run if the comment contains the /merge command.
    if: ${{ github.event.issue.pull_request && github.event.comment.body == '/merge' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
    steps:
      - name: Fast forwarding merging the PR
        uses: sequoia-pgp/fast-forward@v1
        with:
          merge: true
          # To reduce the workflow's verbosity, use 'on-error'
          # to only post a comment when an error occurs, or 'never' to
          # never post a comment.  (In all cases the information is
          # still available in the step's summary.)
          comment: always
