# Post a comment when a pull request is opened, explaining how to run the tests
name: Comment on PR
on:
  pull_request:
    types: [opened]
    branches:
      - dev

jobs:
  comment:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Post comment on PR
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          cat <<EOF > comment.txt
          このプルリクエストに対してテストを実行するには、以下の内容のコメントを投稿してください。
          - テストを実行するには、「/run_tests」
          - テストをスキップするには、「/skip_tests」
          - プルリクエストをマージするには、「/fast_forward」
          EOF
          gh pr \
            comment ${{ github.event.pull_request.number }} \
            --repo ${{ github.repository }} \
            --body "$(cat comment.txt)"
