on:
  workflow_dispatch:
    inputs:
      skip:
        description: "Whether to skip tests"
        type: boolean
        default: false
        required: true

jobs:
  BuildAndTest:
    if: ${{ !inputs.skip }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and run tests
        run: |
          echo "Building and running tests for ref: ${{ github.event.ref }}"
          # Wait for 10 seconds to simulate build time
          sleep 10
          # Add your build and test commands here
          echo "Tests completed successfully."

  BuildAndTestOrSkip:
    needs: [BuildAndTest]
    if: ${{ !cancelled() }}
    runs-on: ubuntu-latest
    steps:
      - name: Check if tests were skipped
        run: |
          if [ '${{ needs.BuildAndTest.result }}' == 'failure' ]; then
            echo "Tests failed."
            exit 1
          elif [ '${{ needs.BuildAndTest.result }}' == 'success' ]; then
            echo "Tests were run successfully."
          else
            echo "Tests were skipped."
          fi
